FROM node:20-bullseye

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY signer-server ./signer-server

ENV SIGNER_HOST=0.0.0.0
ENV SIGNER_PORT=4000

CMD ["node", "signer-server/index.js"]
